let pontosTuristicos = [
    {
      estado: "SP",
      titulo: "Museu do Futebol",
      descricao: "Museu interativo localizado no Estádio do Pacaembu, dedicado à história do futebol no Brasil.",
      horarioFuncionamento: "9h às 17h (terça a domingo)",
      precoIngresso: "R$20,00 (meia-entrada para estudantes e idosos)",
      endereco: "Praça Charles Miller, Pacaembu, São Paulo - SP",
      transportePublico: "Próximo à estação Clínicas do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Exposições Interativas, História do Futebol, Cultura",
      link: "https://museudofutebol.org.br",
      tags: ["museu", "futebol", "esporte", "cultura"]
    },
    {
      estado: "SP",
      titulo: "Edifício Altino Arantes",
      descricao: "O Edifício Altino Arantes é um arranha-céu histórico localizado no centro de São Paulo, conhecido como o 'Empire State Building' paulista e também conhecido como Farol Santander.",
      horarioFuncionamento: "9h às 17h (segunda a sexta)",
      precoIngresso: "Gratuito para a visitação do mirante",
      endereco: "Praça Ramos de Azevedo, 250 - Centro, São Paulo - SP",
      transportePublico: "Próximo à estação República do Metrô",
      estacionamento: "Pago nas imediações",
      acessibilidade: "Sim",
      atracoes: "Mirante com vista panorâmica da cidade, arquitetura histórica",
      link: "https://www.farolsantander.com.br/",
      tags: ["edifício", "arquitetura", "história", "mirante"]
    },
    {
      estado: "SP",
      titulo: "MASP - Museu de Arte de São Paulo",
      descricao: "Um dos museus de arte mais importantes do Brasil, famoso por sua arquitetura e acervo diversificado.",
      horarioFuncionamento: "10h às 18h (terça a domingo), 10h às 20h (quinta-feira)",
      precoIngresso: "R$50,00 (entrada gratuita às terças)",
      endereco: "Av. Paulista, 1578, São Paulo - SP",
      transportePublico: "Próximo à estação Trianon-Masp do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Arte, Exposições, Arquitetura",
      link: "https://masp.org.br",
      tags: ["arte", "museu", "exposição", "cultura"]
    },
    {
      estado: "SP",
      titulo: "Parque da Água Branca",
      descricao: "Um parque voltado para atividades ao ar livre, com feiras de orgânicos, espaço para piqueniques e animais.",
      horarioFuncionamento: "5h30 às 20h",
      precoIngresso: "Entrada gratuita",
      endereco: "Av. Francisco Matarazzo, 455, Água Branca, São Paulo - SP",
      transportePublico: "Próximo à estação Palmeiras-Barra Funda do Metrô",
      estacionamento: "Gratuito",
      acessibilidade: "Sim",
      atracoes: "Natureza, Feiras, Animais, Lazer",
      link: "https://parqueaguabranca.com.br",
      tags: ["parque", "natureza", "família", "feiras"]
    },
    {
      estado: "SP",
      titulo: "Catedral da Sé",
      descricao: "Uma das maiores igrejas do Brasil, localizada no coração de São Paulo, com arquitetura neogótica impressionante.",
      horarioFuncionamento: "8h às 18h",
      precoIngresso: "Entrada gratuita",
      endereco: "Praça da Sé, São Paulo - SP",
      transportePublico: "Próximo à estação Sé do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Arquitetura, História, Religiosidade",
      link: "https://catedraldase.org.br",
      tags: ["igreja", "arquitetura", "religião", "história"]
    },
    {
      estado: "SP",
      titulo: "Edifício Copan",
      descricao: "Ícone da arquitetura modernista, projetado por Oscar Niemeyer, com vista panorâmica da cidade.",
      horarioFuncionamento: "Visitas guiadas (necessário agendamento)",
      precoIngresso: "R$20,00 (visita guiada)",
      endereco: "Av. Ipiranga, 200, República, São Paulo - SP",
      transportePublico: "Próximo à estação República do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Arquitetura, Mirante, História",
      link: "https://edificiocopan.com.br",
      tags: ["arquitetura", "mirante", "história"]
    },
    {
      estado: "SP",
      titulo: "Beco do Batman",
      descricao: "Um dos locais mais icônicos para grafites em São Paulo, localizado no bairro da Vila Madalena.",
      horarioFuncionamento: "24 horas",
      precoIngresso: "Entrada gratuita",
      endereco: "R. Gonçalo Afonso, Vila Madalena, São Paulo - SP",
      transportePublico: "Próximo à estação Fradique Coutinho do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Parcial",
      atracoes: "Grafite, Arte de Rua, Cultura Urbana",
      link: "https://becodobatman.com.br",
      tags: ["grafite", "arte", "cultura", "urbano"]
    },
    {
      estado: "SP",
      titulo: "Parque Villa-Lobos",
      descricao: "Um parque extenso, ideal para caminhadas, ciclismo, esportes e eventos culturais.",
      horarioFuncionamento: "5h30 às 19h",
      precoIngresso: "Entrada gratuita",
      endereco: "Av. Prof. Fonseca Rodrigues, 2001, Alto de Pinheiros, São Paulo - SP",
      transportePublico: "Próximo à estação Villa-Lobos-Jaguaré da CPTM",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Natureza, Pista de Cooper, Ciclovia, Eventos",
      link: "https://parquevillalobos.com.br",
      tags: ["parque", "esportes", "natureza", "família"]
    },
    {
      estado: "SP",
      titulo: "Museu da Imagem e do Som (MIS)",
      descricao: "Um museu dedicado à imagem e ao som, com exposições interativas e eventos culturais.",
      horarioFuncionamento: "11h às 19h (terça a domingo)",
      precoIngresso: "R$30,00 (entrada gratuita às terças)",
      endereco: "Av. Europa, 158, Jardim Europa, São Paulo - SP",
      transportePublico: "Próximo à estação Fradique Coutinho do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Exposições, Cinema, Eventos, Arte Interativa",
      link: "https://mis-sp.org.br",
      tags: ["museu", "arte", "cinema", "exposição"]
    },
    {
      estado: "SP",
      titulo: "Estação da Luz",
      descricao: "Um dos mais belos edifícios históricos da cidade, que abriga a Pinacoteca e o Museu da Língua Portuguesa.",
      horarioFuncionamento: "24 horas (acesso ao prédio); museus têm horários específicos",
      precoIngresso: "Variável conforme o museu",
      endereco: "Praça da Luz, São Paulo - SP",
      transportePublico: "Próximo à estação Luz do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Arquitetura, Museus, História",
      link: "https://estacaodaluz.com.br",
      tags: ["arquitetura", "história", "museu"]
    },
    {
      estado: "SP",
      titulo: "Jardim Botânico de São Paulo",
      descricao: "Um espaço de conservação ambiental com trilhas, lagos e uma variedade de flora.",
      horarioFuncionamento: "9h às 17h",
      precoIngresso: "R$10,00",
      endereco: "Av. Miguel Stéfano, 3031, Água Funda, São Paulo - SP",
      transportePublico: "Próximo à estação Saúde do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Natureza, Trilhas, Lago, Conservação Ambiental",
      link: "https://jardimbotanico.sp.gov.br",
      tags: ["natureza", "trilhas", "conservação", "flora"]
    },
    {
      estado: "SP",
      titulo: "Parque Trianon",
      descricao: "Um parque localizado na Avenida Paulista, ótimo para caminhadas e relaxamento.",
      horarioFuncionamento: "6h às 18h",
      precoIngresso: "Entrada gratuita",
      endereco: "Rua Peixoto Gomide, 949, São Paulo - SP",
      transportePublico: "Próximo à estação Trianon-Masp do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Natureza, Caminhadas, Tranquilidade",
      link: "https://parquetrianon.com.br",
      tags: ["parque", "natureza", "relaxamento"]
    },
    {
      estado: "SP",
      titulo: "Instituto Tomie Ohtake",
      descricao: "Um centro cultural focado em arte contemporânea, com exposições e eventos.",
      horarioFuncionamento: "11h às 20h",
      precoIngresso: "Entrada gratuita",
      endereco: "Rua Coropés, 88, Pinheiros, São Paulo - SP",
      transportePublico: "Próximo à estação Faria Lima do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Arte Contemporânea, Exposições, Eventos",
      link: "https://institutotomieohtake.org.br",
      tags: ["arte", "cultura", "contemporâneo"]
    },
    {
      estado: "SP",
      titulo: "Rua 25 de Março",
      descricao: "Maior centro de comércio popular da América Latina, conhecido por seus preços acessíveis e diversidade de produtos.",
      horarioFuncionamento: "9h às 18h",
      precoIngresso: "Entrada gratuita",
      endereco: "Rua 25 de Março, Centro, São Paulo - SP",
      transportePublico: "Próximo à estação São Bento do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Compras, Comércio Popular, Diversidade",
      link: "https://rua25demarco.com.br",
      tags: ["compras", "comércio", "diversidade"]
    },
    {
      estado: "SP",
      titulo: "Aquário de São Paulo",
      descricao: "O maior aquário da América Latina, com diversas espécies marinhas e atrações interativas.",
      horarioFuncionamento: "10h às 17h",
      precoIngresso: "R$100,00 (inteira), R$50,00 (meia-entrada)",
      endereco: "Rua Huet Bacelar, 407, Ipiranga, São Paulo - SP",
      transportePublico: "Próximo à estação Santos-Imigrantes do Metrô",
      estacionamento: "Pago",
      acessibilidade: "Sim",
      atracoes: "Animais Marinhos, Exposições Interativas, Educação Ambiental",
      link: "https://aquariodesp.com.br",
      tags: ["aquário", "animais", "educação", "família"]
    }
  ];
  